/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClerkRouteRouteImport } from './routes/clerk/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as ClerkAuthenticatedRouteRouteImport } from './routes/clerk/_authenticated/route'
import { Route as ClerkauthRouteRouteImport } from './routes/clerk/(auth)/route'
import { Route as AuthenticatedAnalyticsRouteRouteImport } from './routes/_authenticated/analytics/route'
import { Route as TemplateVendorIdIndexRouteImport } from './routes/template/$vendorId/index'
import { Route as AuthenticatedWalletIndexRouteImport } from './routes/_authenticated/wallet/index'
import { Route as AuthenticatedVendorIndexRouteImport } from './routes/_authenticated/vendor/index'
import { Route as AuthenticatedVendorTemplateIndexRouteImport } from './routes/_authenticated/vendor-template/index'
import { Route as AuthenticatedVendorTemplatePagesIndexRouteImport } from './routes/_authenticated/vendor-template-pages/index'
import { Route as AuthenticatedVendorTemplateOtherIndexRouteImport } from './routes/_authenticated/vendor-template-other/index'
import { Route as AuthenticatedVendorTemplateContactIndexRouteImport } from './routes/_authenticated/vendor-template-contact/index'
import { Route as AuthenticatedVendorTemplateAboutIndexRouteImport } from './routes/_authenticated/vendor-template-about/index'
import { Route as AuthenticatedVendorAnalyticsIndexRouteImport } from './routes/_authenticated/vendor-analytics/index'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedUploadProductsIndexRouteImport } from './routes/_authenticated/upload-products/index'
import { Route as AuthenticatedTemplateWalletIndexRouteImport } from './routes/_authenticated/template-wallet/index'
import { Route as AuthenticatedTemplateOrdersIndexRouteImport } from './routes/_authenticated/template-orders/index'
import { Route as AuthenticatedSitemapsIndexRouteImport } from './routes/_authenticated/sitemaps/index'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated/profile/index'
import { Route as AuthenticatedProductsIndexRouteImport } from './routes/_authenticated/products/index'
import { Route as AuthenticatedPaymentsIndexRouteImport } from './routes/_authenticated/payments/index'
import { Route as AuthenticatedOrderIndexRouteImport } from './routes/_authenticated/order/index'
import { Route as AuthenticatedInventoryManagementIndexRouteImport } from './routes/_authenticated/inventory-management/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedCommissionIndexRouteImport } from './routes/_authenticated/commission/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedCategoryIndexRouteImport } from './routes/_authenticated/category/index'
import { Route as AuthenticatedBorzoReportIndexRouteImport } from './routes/_authenticated/borzo-report/index'
import { Route as AuthenticatedAnalyticsIndexRouteImport } from './routes/_authenticated/analytics/index'
import { Route as TemplateVendorIdRegisterRouteImport } from './routes/template/$vendorId/register'
import { Route as TemplateVendorIdProfileRouteImport } from './routes/template/$vendorId/profile'
import { Route as TemplateVendorIdOrdersRouteImport } from './routes/template/$vendorId/orders'
import { Route as TemplateVendorIdLoginRouteImport } from './routes/template/$vendorId/login'
import { Route as TemplateVendorIdContactRouteImport } from './routes/template/$vendorId/contact'
import { Route as TemplateVendorIdCheckoutRouteImport } from './routes/template/$vendorId/checkout'
import { Route as TemplateVendorIdCartRouteImport } from './routes/template/$vendorId/cart'
import { Route as TemplateVendorIdAboutRouteImport } from './routes/template/$vendorId/about'
import { Route as ClerkAuthenticatedUserManagementRouteImport } from './routes/clerk/_authenticated/user-management'
import { Route as ClerkauthSignUpRouteImport } from './routes/clerk/(auth)/sign-up'
import { Route as ClerkauthSignInRouteImport } from './routes/clerk/(auth)/sign-in'
import { Route as AuthenticatedUsersUserIdRouteImport } from './routes/_authenticated/users/$userId'
import { Route as AuthenticatedPaymentsGatewayRouteImport } from './routes/_authenticated/payments/$gateway'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedAnalyticsTrafficRouteImport } from './routes/_authenticated/analytics/traffic'
import { Route as AuthenticatedAnalyticsReportsRouteImport } from './routes/_authenticated/analytics/reports'
import { Route as AuthenticatedAnalyticsFunnelRouteImport } from './routes/_authenticated/analytics/funnel'
import { Route as AuthenticatedAnalyticsEcommerceRouteImport } from './routes/_authenticated/analytics/ecommerce'
import { Route as AuthenticatedAnalyticsBehaviorRouteImport } from './routes/_authenticated/analytics/behavior'
import { Route as AuthenticatedProductsCreateProductsIndexRouteImport } from './routes/_authenticated/products/create-products/index'
import { Route as AuthenticatedProductsAdminProductsIndexRouteImport } from './routes/_authenticated/products/admin-products/index'
import { Route as AuthenticatedCategoryCreateCategoryIndexRouteImport } from './routes/_authenticated/category/create-category/index'
import { Route as TemplateVendorIdSubcategorySubcategoryIdRouteImport } from './routes/template/$vendorId/subcategory/$subcategoryId'
import { Route as TemplateVendorIdProductProductIdRouteImport } from './routes/template/$vendorId/product/$productId'
import { Route as TemplateVendorIdPagePageSlugRouteImport } from './routes/template/$vendorId/page/$pageSlug'
import { Route as TemplateVendorIdOrdersOrderIdRouteImport } from './routes/template/$vendorId/orders/$orderId'
import { Route as TemplateVendorIdCategoryCategoryIdRouteImport } from './routes/template/$vendorId/category/$categoryId'

const ClerkRouteRoute = ClerkRouteRouteImport.update({
  id: '/clerk',
  path: '/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkAuthenticatedRouteRoute = ClerkAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const ClerkauthRouteRoute = ClerkauthRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const AuthenticatedAnalyticsRouteRoute =
  AuthenticatedAnalyticsRouteRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const TemplateVendorIdIndexRoute = TemplateVendorIdIndexRouteImport.update({
  id: '/template/$vendorId/',
  path: '/template/$vendorId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWalletIndexRoute =
  AuthenticatedWalletIndexRouteImport.update({
    id: '/wallet/',
    path: '/wallet/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendorIndexRoute =
  AuthenticatedVendorIndexRouteImport.update({
    id: '/vendor/',
    path: '/vendor/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendorTemplateIndexRoute =
  AuthenticatedVendorTemplateIndexRouteImport.update({
    id: '/vendor-template/',
    path: '/vendor-template/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendorTemplatePagesIndexRoute =
  AuthenticatedVendorTemplatePagesIndexRouteImport.update({
    id: '/vendor-template-pages/',
    path: '/vendor-template-pages/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendorTemplateOtherIndexRoute =
  AuthenticatedVendorTemplateOtherIndexRouteImport.update({
    id: '/vendor-template-other/',
    path: '/vendor-template-other/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendorTemplateContactIndexRoute =
  AuthenticatedVendorTemplateContactIndexRouteImport.update({
    id: '/vendor-template-contact/',
    path: '/vendor-template-contact/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendorTemplateAboutIndexRoute =
  AuthenticatedVendorTemplateAboutIndexRouteImport.update({
    id: '/vendor-template-about/',
    path: '/vendor-template-about/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendorAnalyticsIndexRoute =
  AuthenticatedVendorAnalyticsIndexRouteImport.update({
    id: '/vendor-analytics/',
    path: '/vendor-analytics/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUploadProductsIndexRoute =
  AuthenticatedUploadProductsIndexRouteImport.update({
    id: '/upload-products/',
    path: '/upload-products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTemplateWalletIndexRoute =
  AuthenticatedTemplateWalletIndexRouteImport.update({
    id: '/template-wallet/',
    path: '/template-wallet/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTemplateOrdersIndexRoute =
  AuthenticatedTemplateOrdersIndexRouteImport.update({
    id: '/template-orders/',
    path: '/template-orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSitemapsIndexRoute =
  AuthenticatedSitemapsIndexRouteImport.update({
    id: '/sitemaps/',
    path: '/sitemaps/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsIndexRoute =
  AuthenticatedProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaymentsIndexRoute =
  AuthenticatedPaymentsIndexRouteImport.update({
    id: '/payments/',
    path: '/payments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrderIndexRoute = AuthenticatedOrderIndexRouteImport.update({
  id: '/order/',
  path: '/order/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryManagementIndexRoute =
  AuthenticatedInventoryManagementIndexRouteImport.update({
    id: '/inventory-management/',
    path: '/inventory-management/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommissionIndexRoute =
  AuthenticatedCommissionIndexRouteImport.update({
    id: '/commission/',
    path: '/commission/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCategoryIndexRoute =
  AuthenticatedCategoryIndexRouteImport.update({
    id: '/category/',
    path: '/category/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBorzoReportIndexRoute =
  AuthenticatedBorzoReportIndexRouteImport.update({
    id: '/borzo-report/',
    path: '/borzo-report/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsIndexRoute =
  AuthenticatedAnalyticsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAnalyticsRouteRoute,
  } as any)
const TemplateVendorIdRegisterRoute =
  TemplateVendorIdRegisterRouteImport.update({
    id: '/template/$vendorId/register',
    path: '/template/$vendorId/register',
    getParentRoute: () => rootRouteImport,
  } as any)
const TemplateVendorIdProfileRoute = TemplateVendorIdProfileRouteImport.update({
  id: '/template/$vendorId/profile',
  path: '/template/$vendorId/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplateVendorIdOrdersRoute = TemplateVendorIdOrdersRouteImport.update({
  id: '/template/$vendorId/orders',
  path: '/template/$vendorId/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplateVendorIdLoginRoute = TemplateVendorIdLoginRouteImport.update({
  id: '/template/$vendorId/login',
  path: '/template/$vendorId/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplateVendorIdContactRoute = TemplateVendorIdContactRouteImport.update({
  id: '/template/$vendorId/contact',
  path: '/template/$vendorId/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplateVendorIdCheckoutRoute =
  TemplateVendorIdCheckoutRouteImport.update({
    id: '/template/$vendorId/checkout',
    path: '/template/$vendorId/checkout',
    getParentRoute: () => rootRouteImport,
  } as any)
const TemplateVendorIdCartRoute = TemplateVendorIdCartRouteImport.update({
  id: '/template/$vendorId/cart',
  path: '/template/$vendorId/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplateVendorIdAboutRoute = TemplateVendorIdAboutRouteImport.update({
  id: '/template/$vendorId/about',
  path: '/template/$vendorId/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkAuthenticatedUserManagementRoute =
  ClerkAuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => ClerkAuthenticatedRouteRoute,
  } as any)
const ClerkauthSignUpRoute = ClerkauthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const ClerkauthSignInRoute = ClerkauthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const AuthenticatedUsersUserIdRoute =
  AuthenticatedUsersUserIdRouteImport.update({
    id: '/users/$userId',
    path: '/users/$userId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaymentsGatewayRoute =
  AuthenticatedPaymentsGatewayRouteImport.update({
    id: '/payments/$gateway',
    path: '/payments/$gateway',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsTrafficRoute =
  AuthenticatedAnalyticsTrafficRouteImport.update({
    id: '/traffic',
    path: '/traffic',
    getParentRoute: () => AuthenticatedAnalyticsRouteRoute,
  } as any)
const AuthenticatedAnalyticsReportsRoute =
  AuthenticatedAnalyticsReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAnalyticsRouteRoute,
  } as any)
const AuthenticatedAnalyticsFunnelRoute =
  AuthenticatedAnalyticsFunnelRouteImport.update({
    id: '/funnel',
    path: '/funnel',
    getParentRoute: () => AuthenticatedAnalyticsRouteRoute,
  } as any)
const AuthenticatedAnalyticsEcommerceRoute =
  AuthenticatedAnalyticsEcommerceRouteImport.update({
    id: '/ecommerce',
    path: '/ecommerce',
    getParentRoute: () => AuthenticatedAnalyticsRouteRoute,
  } as any)
const AuthenticatedAnalyticsBehaviorRoute =
  AuthenticatedAnalyticsBehaviorRouteImport.update({
    id: '/behavior',
    path: '/behavior',
    getParentRoute: () => AuthenticatedAnalyticsRouteRoute,
  } as any)
const AuthenticatedProductsCreateProductsIndexRoute =
  AuthenticatedProductsCreateProductsIndexRouteImport.update({
    id: '/products/create-products/',
    path: '/products/create-products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsAdminProductsIndexRoute =
  AuthenticatedProductsAdminProductsIndexRouteImport.update({
    id: '/products/admin-products/',
    path: '/products/admin-products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCategoryCreateCategoryIndexRoute =
  AuthenticatedCategoryCreateCategoryIndexRouteImport.update({
    id: '/category/create-category/',
    path: '/category/create-category/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const TemplateVendorIdSubcategorySubcategoryIdRoute =
  TemplateVendorIdSubcategorySubcategoryIdRouteImport.update({
    id: '/template/$vendorId/subcategory/$subcategoryId',
    path: '/template/$vendorId/subcategory/$subcategoryId',
    getParentRoute: () => rootRouteImport,
  } as any)
const TemplateVendorIdProductProductIdRoute =
  TemplateVendorIdProductProductIdRouteImport.update({
    id: '/template/$vendorId/product/$productId',
    path: '/template/$vendorId/product/$productId',
    getParentRoute: () => rootRouteImport,
  } as any)
const TemplateVendorIdPagePageSlugRoute =
  TemplateVendorIdPagePageSlugRouteImport.update({
    id: '/template/$vendorId/page/$pageSlug',
    path: '/template/$vendorId/page/$pageSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const TemplateVendorIdOrdersOrderIdRoute =
  TemplateVendorIdOrdersOrderIdRouteImport.update({
    id: '/$orderId',
    path: '/$orderId',
    getParentRoute: () => TemplateVendorIdOrdersRoute,
  } as any)
const TemplateVendorIdCategoryCategoryIdRoute =
  TemplateVendorIdCategoryCategoryIdRouteImport.update({
    id: '/template/$vendorId/category/$categoryId',
    path: '/template/$vendorId/category/$categoryId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/analytics': typeof AuthenticatedAnalyticsRouteRouteWithChildren
  '/clerk/': typeof ClerkauthRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/analytics/behavior': typeof AuthenticatedAnalyticsBehaviorRoute
  '/analytics/ecommerce': typeof AuthenticatedAnalyticsEcommerceRoute
  '/analytics/funnel': typeof AuthenticatedAnalyticsFunnelRoute
  '/analytics/reports': typeof AuthenticatedAnalyticsReportsRoute
  '/analytics/traffic': typeof AuthenticatedAnalyticsTrafficRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/payments/$gateway': typeof AuthenticatedPaymentsGatewayRoute
  '/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/template/$vendorId/about': typeof TemplateVendorIdAboutRoute
  '/template/$vendorId/cart': typeof TemplateVendorIdCartRoute
  '/template/$vendorId/checkout': typeof TemplateVendorIdCheckoutRoute
  '/template/$vendorId/contact': typeof TemplateVendorIdContactRoute
  '/template/$vendorId/login': typeof TemplateVendorIdLoginRoute
  '/template/$vendorId/orders': typeof TemplateVendorIdOrdersRouteWithChildren
  '/template/$vendorId/profile': typeof TemplateVendorIdProfileRoute
  '/template/$vendorId/register': typeof TemplateVendorIdRegisterRoute
  '/analytics/': typeof AuthenticatedAnalyticsIndexRoute
  '/borzo-report': typeof AuthenticatedBorzoReportIndexRoute
  '/category': typeof AuthenticatedCategoryIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/commission': typeof AuthenticatedCommissionIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/inventory-management': typeof AuthenticatedInventoryManagementIndexRoute
  '/order': typeof AuthenticatedOrderIndexRoute
  '/payments': typeof AuthenticatedPaymentsIndexRoute
  '/products': typeof AuthenticatedProductsIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/sitemaps': typeof AuthenticatedSitemapsIndexRoute
  '/template-orders': typeof AuthenticatedTemplateOrdersIndexRoute
  '/template-wallet': typeof AuthenticatedTemplateWalletIndexRoute
  '/upload-products': typeof AuthenticatedUploadProductsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/vendor-analytics': typeof AuthenticatedVendorAnalyticsIndexRoute
  '/vendor-template-about': typeof AuthenticatedVendorTemplateAboutIndexRoute
  '/vendor-template-contact': typeof AuthenticatedVendorTemplateContactIndexRoute
  '/vendor-template-other': typeof AuthenticatedVendorTemplateOtherIndexRoute
  '/vendor-template-pages': typeof AuthenticatedVendorTemplatePagesIndexRoute
  '/vendor-template': typeof AuthenticatedVendorTemplateIndexRoute
  '/vendor': typeof AuthenticatedVendorIndexRoute
  '/wallet': typeof AuthenticatedWalletIndexRoute
  '/template/$vendorId': typeof TemplateVendorIdIndexRoute
  '/template/$vendorId/category/$categoryId': typeof TemplateVendorIdCategoryCategoryIdRoute
  '/template/$vendorId/orders/$orderId': typeof TemplateVendorIdOrdersOrderIdRoute
  '/template/$vendorId/page/$pageSlug': typeof TemplateVendorIdPagePageSlugRoute
  '/template/$vendorId/product/$productId': typeof TemplateVendorIdProductProductIdRoute
  '/template/$vendorId/subcategory/$subcategoryId': typeof TemplateVendorIdSubcategorySubcategoryIdRoute
  '/category/create-category': typeof AuthenticatedCategoryCreateCategoryIndexRoute
  '/products/admin-products': typeof AuthenticatedProductsAdminProductsIndexRoute
  '/products/create-products': typeof AuthenticatedProductsCreateProductsIndexRoute
}
export interface FileRoutesByTo {
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/analytics/behavior': typeof AuthenticatedAnalyticsBehaviorRoute
  '/analytics/ecommerce': typeof AuthenticatedAnalyticsEcommerceRoute
  '/analytics/funnel': typeof AuthenticatedAnalyticsFunnelRoute
  '/analytics/reports': typeof AuthenticatedAnalyticsReportsRoute
  '/analytics/traffic': typeof AuthenticatedAnalyticsTrafficRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/payments/$gateway': typeof AuthenticatedPaymentsGatewayRoute
  '/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/template/$vendorId/about': typeof TemplateVendorIdAboutRoute
  '/template/$vendorId/cart': typeof TemplateVendorIdCartRoute
  '/template/$vendorId/checkout': typeof TemplateVendorIdCheckoutRoute
  '/template/$vendorId/contact': typeof TemplateVendorIdContactRoute
  '/template/$vendorId/login': typeof TemplateVendorIdLoginRoute
  '/template/$vendorId/orders': typeof TemplateVendorIdOrdersRouteWithChildren
  '/template/$vendorId/profile': typeof TemplateVendorIdProfileRoute
  '/template/$vendorId/register': typeof TemplateVendorIdRegisterRoute
  '/analytics': typeof AuthenticatedAnalyticsIndexRoute
  '/borzo-report': typeof AuthenticatedBorzoReportIndexRoute
  '/category': typeof AuthenticatedCategoryIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/commission': typeof AuthenticatedCommissionIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/inventory-management': typeof AuthenticatedInventoryManagementIndexRoute
  '/order': typeof AuthenticatedOrderIndexRoute
  '/payments': typeof AuthenticatedPaymentsIndexRoute
  '/products': typeof AuthenticatedProductsIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/sitemaps': typeof AuthenticatedSitemapsIndexRoute
  '/template-orders': typeof AuthenticatedTemplateOrdersIndexRoute
  '/template-wallet': typeof AuthenticatedTemplateWalletIndexRoute
  '/upload-products': typeof AuthenticatedUploadProductsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/vendor-analytics': typeof AuthenticatedVendorAnalyticsIndexRoute
  '/vendor-template-about': typeof AuthenticatedVendorTemplateAboutIndexRoute
  '/vendor-template-contact': typeof AuthenticatedVendorTemplateContactIndexRoute
  '/vendor-template-other': typeof AuthenticatedVendorTemplateOtherIndexRoute
  '/vendor-template-pages': typeof AuthenticatedVendorTemplatePagesIndexRoute
  '/vendor-template': typeof AuthenticatedVendorTemplateIndexRoute
  '/vendor': typeof AuthenticatedVendorIndexRoute
  '/wallet': typeof AuthenticatedWalletIndexRoute
  '/template/$vendorId': typeof TemplateVendorIdIndexRoute
  '/template/$vendorId/category/$categoryId': typeof TemplateVendorIdCategoryCategoryIdRoute
  '/template/$vendorId/orders/$orderId': typeof TemplateVendorIdOrdersOrderIdRoute
  '/template/$vendorId/page/$pageSlug': typeof TemplateVendorIdPagePageSlugRoute
  '/template/$vendorId/product/$productId': typeof TemplateVendorIdProductProductIdRoute
  '/template/$vendorId/subcategory/$subcategoryId': typeof TemplateVendorIdSubcategorySubcategoryIdRoute
  '/category/create-category': typeof AuthenticatedCategoryCreateCategoryIndexRoute
  '/products/admin-products': typeof AuthenticatedProductsAdminProductsIndexRoute
  '/products/create-products': typeof AuthenticatedProductsCreateProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/clerk': typeof ClerkRouteRouteWithChildren
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRouteRouteWithChildren
  '/clerk/(auth)': typeof ClerkauthRouteRouteWithChildren
  '/clerk/_authenticated': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/analytics/behavior': typeof AuthenticatedAnalyticsBehaviorRoute
  '/_authenticated/analytics/ecommerce': typeof AuthenticatedAnalyticsEcommerceRoute
  '/_authenticated/analytics/funnel': typeof AuthenticatedAnalyticsFunnelRoute
  '/_authenticated/analytics/reports': typeof AuthenticatedAnalyticsReportsRoute
  '/_authenticated/analytics/traffic': typeof AuthenticatedAnalyticsTrafficRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/payments/$gateway': typeof AuthenticatedPaymentsGatewayRoute
  '/_authenticated/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/clerk/(auth)/sign-in': typeof ClerkauthSignInRoute
  '/clerk/(auth)/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/_authenticated/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/template/$vendorId/about': typeof TemplateVendorIdAboutRoute
  '/template/$vendorId/cart': typeof TemplateVendorIdCartRoute
  '/template/$vendorId/checkout': typeof TemplateVendorIdCheckoutRoute
  '/template/$vendorId/contact': typeof TemplateVendorIdContactRoute
  '/template/$vendorId/login': typeof TemplateVendorIdLoginRoute
  '/template/$vendorId/orders': typeof TemplateVendorIdOrdersRouteWithChildren
  '/template/$vendorId/profile': typeof TemplateVendorIdProfileRoute
  '/template/$vendorId/register': typeof TemplateVendorIdRegisterRoute
  '/_authenticated/analytics/': typeof AuthenticatedAnalyticsIndexRoute
  '/_authenticated/borzo-report/': typeof AuthenticatedBorzoReportIndexRoute
  '/_authenticated/category/': typeof AuthenticatedCategoryIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/commission/': typeof AuthenticatedCommissionIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/inventory-management/': typeof AuthenticatedInventoryManagementIndexRoute
  '/_authenticated/order/': typeof AuthenticatedOrderIndexRoute
  '/_authenticated/payments/': typeof AuthenticatedPaymentsIndexRoute
  '/_authenticated/products/': typeof AuthenticatedProductsIndexRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
  '/_authenticated/sitemaps/': typeof AuthenticatedSitemapsIndexRoute
  '/_authenticated/template-orders/': typeof AuthenticatedTemplateOrdersIndexRoute
  '/_authenticated/template-wallet/': typeof AuthenticatedTemplateWalletIndexRoute
  '/_authenticated/upload-products/': typeof AuthenticatedUploadProductsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/vendor-analytics/': typeof AuthenticatedVendorAnalyticsIndexRoute
  '/_authenticated/vendor-template-about/': typeof AuthenticatedVendorTemplateAboutIndexRoute
  '/_authenticated/vendor-template-contact/': typeof AuthenticatedVendorTemplateContactIndexRoute
  '/_authenticated/vendor-template-other/': typeof AuthenticatedVendorTemplateOtherIndexRoute
  '/_authenticated/vendor-template-pages/': typeof AuthenticatedVendorTemplatePagesIndexRoute
  '/_authenticated/vendor-template/': typeof AuthenticatedVendorTemplateIndexRoute
  '/_authenticated/vendor/': typeof AuthenticatedVendorIndexRoute
  '/_authenticated/wallet/': typeof AuthenticatedWalletIndexRoute
  '/template/$vendorId/': typeof TemplateVendorIdIndexRoute
  '/template/$vendorId/category/$categoryId': typeof TemplateVendorIdCategoryCategoryIdRoute
  '/template/$vendorId/orders/$orderId': typeof TemplateVendorIdOrdersOrderIdRoute
  '/template/$vendorId/page/$pageSlug': typeof TemplateVendorIdPagePageSlugRoute
  '/template/$vendorId/product/$productId': typeof TemplateVendorIdProductProductIdRoute
  '/template/$vendorId/subcategory/$subcategoryId': typeof TemplateVendorIdSubcategorySubcategoryIdRoute
  '/_authenticated/category/create-category/': typeof AuthenticatedCategoryCreateCategoryIndexRoute
  '/_authenticated/products/admin-products/': typeof AuthenticatedProductsAdminProductsIndexRoute
  '/_authenticated/products/create-products/': typeof AuthenticatedProductsCreateProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/clerk'
    | '/analytics'
    | '/clerk/'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/analytics/behavior'
    | '/analytics/ecommerce'
    | '/analytics/funnel'
    | '/analytics/reports'
    | '/analytics/traffic'
    | '/errors/$error'
    | '/payments/$gateway'
    | '/users/$userId'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/template/$vendorId/about'
    | '/template/$vendorId/cart'
    | '/template/$vendorId/checkout'
    | '/template/$vendorId/contact'
    | '/template/$vendorId/login'
    | '/template/$vendorId/orders'
    | '/template/$vendorId/profile'
    | '/template/$vendorId/register'
    | '/analytics/'
    | '/borzo-report'
    | '/category'
    | '/chats'
    | '/commission'
    | '/help-center'
    | '/inventory-management'
    | '/order'
    | '/payments'
    | '/products'
    | '/profile'
    | '/sitemaps'
    | '/template-orders'
    | '/template-wallet'
    | '/upload-products'
    | '/users'
    | '/vendor-analytics'
    | '/vendor-template-about'
    | '/vendor-template-contact'
    | '/vendor-template-other'
    | '/vendor-template-pages'
    | '/vendor-template'
    | '/vendor'
    | '/wallet'
    | '/template/$vendorId'
    | '/template/$vendorId/category/$categoryId'
    | '/template/$vendorId/orders/$orderId'
    | '/template/$vendorId/page/$pageSlug'
    | '/template/$vendorId/product/$productId'
    | '/template/$vendorId/subcategory/$subcategoryId'
    | '/category/create-category'
    | '/products/admin-products'
    | '/products/create-products'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/clerk'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/analytics/behavior'
    | '/analytics/ecommerce'
    | '/analytics/funnel'
    | '/analytics/reports'
    | '/analytics/traffic'
    | '/errors/$error'
    | '/payments/$gateway'
    | '/users/$userId'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/template/$vendorId/about'
    | '/template/$vendorId/cart'
    | '/template/$vendorId/checkout'
    | '/template/$vendorId/contact'
    | '/template/$vendorId/login'
    | '/template/$vendorId/orders'
    | '/template/$vendorId/profile'
    | '/template/$vendorId/register'
    | '/analytics'
    | '/borzo-report'
    | '/category'
    | '/chats'
    | '/commission'
    | '/help-center'
    | '/inventory-management'
    | '/order'
    | '/payments'
    | '/products'
    | '/profile'
    | '/sitemaps'
    | '/template-orders'
    | '/template-wallet'
    | '/upload-products'
    | '/users'
    | '/vendor-analytics'
    | '/vendor-template-about'
    | '/vendor-template-contact'
    | '/vendor-template-other'
    | '/vendor-template-pages'
    | '/vendor-template'
    | '/vendor'
    | '/wallet'
    | '/template/$vendorId'
    | '/template/$vendorId/category/$categoryId'
    | '/template/$vendorId/orders/$orderId'
    | '/template/$vendorId/page/$pageSlug'
    | '/template/$vendorId/product/$productId'
    | '/template/$vendorId/subcategory/$subcategoryId'
    | '/category/create-category'
    | '/products/admin-products'
    | '/products/create-products'
  id:
    | '__root__'
    | '/_authenticated'
    | '/clerk'
    | '/_authenticated/analytics'
    | '/clerk/(auth)'
    | '/clerk/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/analytics/behavior'
    | '/_authenticated/analytics/ecommerce'
    | '/_authenticated/analytics/funnel'
    | '/_authenticated/analytics/reports'
    | '/_authenticated/analytics/traffic'
    | '/_authenticated/errors/$error'
    | '/_authenticated/payments/$gateway'
    | '/_authenticated/users/$userId'
    | '/clerk/(auth)/sign-in'
    | '/clerk/(auth)/sign-up'
    | '/clerk/_authenticated/user-management'
    | '/template/$vendorId/about'
    | '/template/$vendorId/cart'
    | '/template/$vendorId/checkout'
    | '/template/$vendorId/contact'
    | '/template/$vendorId/login'
    | '/template/$vendorId/orders'
    | '/template/$vendorId/profile'
    | '/template/$vendorId/register'
    | '/_authenticated/analytics/'
    | '/_authenticated/borzo-report/'
    | '/_authenticated/category/'
    | '/_authenticated/chats/'
    | '/_authenticated/commission/'
    | '/_authenticated/help-center/'
    | '/_authenticated/inventory-management/'
    | '/_authenticated/order/'
    | '/_authenticated/payments/'
    | '/_authenticated/products/'
    | '/_authenticated/profile/'
    | '/_authenticated/sitemaps/'
    | '/_authenticated/template-orders/'
    | '/_authenticated/template-wallet/'
    | '/_authenticated/upload-products/'
    | '/_authenticated/users/'
    | '/_authenticated/vendor-analytics/'
    | '/_authenticated/vendor-template-about/'
    | '/_authenticated/vendor-template-contact/'
    | '/_authenticated/vendor-template-other/'
    | '/_authenticated/vendor-template-pages/'
    | '/_authenticated/vendor-template/'
    | '/_authenticated/vendor/'
    | '/_authenticated/wallet/'
    | '/template/$vendorId/'
    | '/template/$vendorId/category/$categoryId'
    | '/template/$vendorId/orders/$orderId'
    | '/template/$vendorId/page/$pageSlug'
    | '/template/$vendorId/product/$productId'
    | '/template/$vendorId/subcategory/$subcategoryId'
    | '/_authenticated/category/create-category/'
    | '/_authenticated/products/admin-products/'
    | '/_authenticated/products/create-products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ClerkRouteRoute: typeof ClerkRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  TemplateVendorIdAboutRoute: typeof TemplateVendorIdAboutRoute
  TemplateVendorIdCartRoute: typeof TemplateVendorIdCartRoute
  TemplateVendorIdCheckoutRoute: typeof TemplateVendorIdCheckoutRoute
  TemplateVendorIdContactRoute: typeof TemplateVendorIdContactRoute
  TemplateVendorIdLoginRoute: typeof TemplateVendorIdLoginRoute
  TemplateVendorIdOrdersRoute: typeof TemplateVendorIdOrdersRouteWithChildren
  TemplateVendorIdProfileRoute: typeof TemplateVendorIdProfileRoute
  TemplateVendorIdRegisterRoute: typeof TemplateVendorIdRegisterRoute
  TemplateVendorIdIndexRoute: typeof TemplateVendorIdIndexRoute
  TemplateVendorIdCategoryCategoryIdRoute: typeof TemplateVendorIdCategoryCategoryIdRoute
  TemplateVendorIdPagePageSlugRoute: typeof TemplateVendorIdPagePageSlugRoute
  TemplateVendorIdProductProductIdRoute: typeof TemplateVendorIdProductProductIdRoute
  TemplateVendorIdSubcategorySubcategoryIdRoute: typeof TemplateVendorIdSubcategorySubcategoryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/clerk': {
      id: '/clerk'
      path: '/clerk'
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk/_authenticated': {
      id: '/clerk/_authenticated'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkAuthenticatedRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/clerk/(auth)': {
      id: '/clerk/(auth)'
      path: '/'
      fullPath: '/clerk/'
      preLoaderRoute: typeof ClerkauthRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/template/$vendorId/': {
      id: '/template/$vendorId/'
      path: '/template/$vendorId'
      fullPath: '/template/$vendorId'
      preLoaderRoute: typeof TemplateVendorIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wallet/': {
      id: '/_authenticated/wallet/'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendor/': {
      id: '/_authenticated/vendor/'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof AuthenticatedVendorIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendor-template/': {
      id: '/_authenticated/vendor-template/'
      path: '/vendor-template'
      fullPath: '/vendor-template'
      preLoaderRoute: typeof AuthenticatedVendorTemplateIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendor-template-pages/': {
      id: '/_authenticated/vendor-template-pages/'
      path: '/vendor-template-pages'
      fullPath: '/vendor-template-pages'
      preLoaderRoute: typeof AuthenticatedVendorTemplatePagesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendor-template-other/': {
      id: '/_authenticated/vendor-template-other/'
      path: '/vendor-template-other'
      fullPath: '/vendor-template-other'
      preLoaderRoute: typeof AuthenticatedVendorTemplateOtherIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendor-template-contact/': {
      id: '/_authenticated/vendor-template-contact/'
      path: '/vendor-template-contact'
      fullPath: '/vendor-template-contact'
      preLoaderRoute: typeof AuthenticatedVendorTemplateContactIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendor-template-about/': {
      id: '/_authenticated/vendor-template-about/'
      path: '/vendor-template-about'
      fullPath: '/vendor-template-about'
      preLoaderRoute: typeof AuthenticatedVendorTemplateAboutIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendor-analytics/': {
      id: '/_authenticated/vendor-analytics/'
      path: '/vendor-analytics'
      fullPath: '/vendor-analytics'
      preLoaderRoute: typeof AuthenticatedVendorAnalyticsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/upload-products/': {
      id: '/_authenticated/upload-products/'
      path: '/upload-products'
      fullPath: '/upload-products'
      preLoaderRoute: typeof AuthenticatedUploadProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/template-wallet/': {
      id: '/_authenticated/template-wallet/'
      path: '/template-wallet'
      fullPath: '/template-wallet'
      preLoaderRoute: typeof AuthenticatedTemplateWalletIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/template-orders/': {
      id: '/_authenticated/template-orders/'
      path: '/template-orders'
      fullPath: '/template-orders'
      preLoaderRoute: typeof AuthenticatedTemplateOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sitemaps/': {
      id: '/_authenticated/sitemaps/'
      path: '/sitemaps'
      fullPath: '/sitemaps'
      preLoaderRoute: typeof AuthenticatedSitemapsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/': {
      id: '/_authenticated/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments/': {
      id: '/_authenticated/payments/'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/order/': {
      id: '/_authenticated/order/'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof AuthenticatedOrderIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory-management/': {
      id: '/_authenticated/inventory-management/'
      path: '/inventory-management'
      fullPath: '/inventory-management'
      preLoaderRoute: typeof AuthenticatedInventoryManagementIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/commission/': {
      id: '/_authenticated/commission/'
      path: '/commission'
      fullPath: '/commission'
      preLoaderRoute: typeof AuthenticatedCommissionIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/category/': {
      id: '/_authenticated/category/'
      path: '/category'
      fullPath: '/category'
      preLoaderRoute: typeof AuthenticatedCategoryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/borzo-report/': {
      id: '/_authenticated/borzo-report/'
      path: '/borzo-report'
      fullPath: '/borzo-report'
      preLoaderRoute: typeof AuthenticatedBorzoReportIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics/': {
      id: '/_authenticated/analytics/'
      path: '/'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AuthenticatedAnalyticsIndexRouteImport
      parentRoute: typeof AuthenticatedAnalyticsRouteRoute
    }
    '/template/$vendorId/register': {
      id: '/template/$vendorId/register'
      path: '/template/$vendorId/register'
      fullPath: '/template/$vendorId/register'
      preLoaderRoute: typeof TemplateVendorIdRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/template/$vendorId/profile': {
      id: '/template/$vendorId/profile'
      path: '/template/$vendorId/profile'
      fullPath: '/template/$vendorId/profile'
      preLoaderRoute: typeof TemplateVendorIdProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/template/$vendorId/orders': {
      id: '/template/$vendorId/orders'
      path: '/template/$vendorId/orders'
      fullPath: '/template/$vendorId/orders'
      preLoaderRoute: typeof TemplateVendorIdOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/template/$vendorId/login': {
      id: '/template/$vendorId/login'
      path: '/template/$vendorId/login'
      fullPath: '/template/$vendorId/login'
      preLoaderRoute: typeof TemplateVendorIdLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/template/$vendorId/contact': {
      id: '/template/$vendorId/contact'
      path: '/template/$vendorId/contact'
      fullPath: '/template/$vendorId/contact'
      preLoaderRoute: typeof TemplateVendorIdContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/template/$vendorId/checkout': {
      id: '/template/$vendorId/checkout'
      path: '/template/$vendorId/checkout'
      fullPath: '/template/$vendorId/checkout'
      preLoaderRoute: typeof TemplateVendorIdCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/template/$vendorId/cart': {
      id: '/template/$vendorId/cart'
      path: '/template/$vendorId/cart'
      fullPath: '/template/$vendorId/cart'
      preLoaderRoute: typeof TemplateVendorIdCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/template/$vendorId/about': {
      id: '/template/$vendorId/about'
      path: '/template/$vendorId/about'
      fullPath: '/template/$vendorId/about'
      preLoaderRoute: typeof TemplateVendorIdAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk/_authenticated/user-management': {
      id: '/clerk/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/clerk/user-management'
      preLoaderRoute: typeof ClerkAuthenticatedUserManagementRouteImport
      parentRoute: typeof ClerkAuthenticatedRouteRoute
    }
    '/clerk/(auth)/sign-up': {
      id: '/clerk/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/clerk/sign-up'
      preLoaderRoute: typeof ClerkauthSignUpRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/clerk/(auth)/sign-in': {
      id: '/clerk/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/clerk/sign-in'
      preLoaderRoute: typeof ClerkauthSignInRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/_authenticated/users/$userId': {
      id: '/_authenticated/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AuthenticatedUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments/$gateway': {
      id: '/_authenticated/payments/$gateway'
      path: '/payments/$gateway'
      fullPath: '/payments/$gateway'
      preLoaderRoute: typeof AuthenticatedPaymentsGatewayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics/traffic': {
      id: '/_authenticated/analytics/traffic'
      path: '/traffic'
      fullPath: '/analytics/traffic'
      preLoaderRoute: typeof AuthenticatedAnalyticsTrafficRouteImport
      parentRoute: typeof AuthenticatedAnalyticsRouteRoute
    }
    '/_authenticated/analytics/reports': {
      id: '/_authenticated/analytics/reports'
      path: '/reports'
      fullPath: '/analytics/reports'
      preLoaderRoute: typeof AuthenticatedAnalyticsReportsRouteImport
      parentRoute: typeof AuthenticatedAnalyticsRouteRoute
    }
    '/_authenticated/analytics/funnel': {
      id: '/_authenticated/analytics/funnel'
      path: '/funnel'
      fullPath: '/analytics/funnel'
      preLoaderRoute: typeof AuthenticatedAnalyticsFunnelRouteImport
      parentRoute: typeof AuthenticatedAnalyticsRouteRoute
    }
    '/_authenticated/analytics/ecommerce': {
      id: '/_authenticated/analytics/ecommerce'
      path: '/ecommerce'
      fullPath: '/analytics/ecommerce'
      preLoaderRoute: typeof AuthenticatedAnalyticsEcommerceRouteImport
      parentRoute: typeof AuthenticatedAnalyticsRouteRoute
    }
    '/_authenticated/analytics/behavior': {
      id: '/_authenticated/analytics/behavior'
      path: '/behavior'
      fullPath: '/analytics/behavior'
      preLoaderRoute: typeof AuthenticatedAnalyticsBehaviorRouteImport
      parentRoute: typeof AuthenticatedAnalyticsRouteRoute
    }
    '/_authenticated/products/create-products/': {
      id: '/_authenticated/products/create-products/'
      path: '/products/create-products'
      fullPath: '/products/create-products'
      preLoaderRoute: typeof AuthenticatedProductsCreateProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/admin-products/': {
      id: '/_authenticated/products/admin-products/'
      path: '/products/admin-products'
      fullPath: '/products/admin-products'
      preLoaderRoute: typeof AuthenticatedProductsAdminProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/category/create-category/': {
      id: '/_authenticated/category/create-category/'
      path: '/category/create-category'
      fullPath: '/category/create-category'
      preLoaderRoute: typeof AuthenticatedCategoryCreateCategoryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/template/$vendorId/subcategory/$subcategoryId': {
      id: '/template/$vendorId/subcategory/$subcategoryId'
      path: '/template/$vendorId/subcategory/$subcategoryId'
      fullPath: '/template/$vendorId/subcategory/$subcategoryId'
      preLoaderRoute: typeof TemplateVendorIdSubcategorySubcategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/template/$vendorId/product/$productId': {
      id: '/template/$vendorId/product/$productId'
      path: '/template/$vendorId/product/$productId'
      fullPath: '/template/$vendorId/product/$productId'
      preLoaderRoute: typeof TemplateVendorIdProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/template/$vendorId/page/$pageSlug': {
      id: '/template/$vendorId/page/$pageSlug'
      path: '/template/$vendorId/page/$pageSlug'
      fullPath: '/template/$vendorId/page/$pageSlug'
      preLoaderRoute: typeof TemplateVendorIdPagePageSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/template/$vendorId/orders/$orderId': {
      id: '/template/$vendorId/orders/$orderId'
      path: '/$orderId'
      fullPath: '/template/$vendorId/orders/$orderId'
      preLoaderRoute: typeof TemplateVendorIdOrdersOrderIdRouteImport
      parentRoute: typeof TemplateVendorIdOrdersRoute
    }
    '/template/$vendorId/category/$categoryId': {
      id: '/template/$vendorId/category/$categoryId'
      path: '/template/$vendorId/category/$categoryId'
      fullPath: '/template/$vendorId/category/$categoryId'
      preLoaderRoute: typeof TemplateVendorIdCategoryCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAnalyticsRouteRouteChildren {
  AuthenticatedAnalyticsBehaviorRoute: typeof AuthenticatedAnalyticsBehaviorRoute
  AuthenticatedAnalyticsEcommerceRoute: typeof AuthenticatedAnalyticsEcommerceRoute
  AuthenticatedAnalyticsFunnelRoute: typeof AuthenticatedAnalyticsFunnelRoute
  AuthenticatedAnalyticsReportsRoute: typeof AuthenticatedAnalyticsReportsRoute
  AuthenticatedAnalyticsTrafficRoute: typeof AuthenticatedAnalyticsTrafficRoute
  AuthenticatedAnalyticsIndexRoute: typeof AuthenticatedAnalyticsIndexRoute
}

const AuthenticatedAnalyticsRouteRouteChildren: AuthenticatedAnalyticsRouteRouteChildren =
  {
    AuthenticatedAnalyticsBehaviorRoute: AuthenticatedAnalyticsBehaviorRoute,
    AuthenticatedAnalyticsEcommerceRoute: AuthenticatedAnalyticsEcommerceRoute,
    AuthenticatedAnalyticsFunnelRoute: AuthenticatedAnalyticsFunnelRoute,
    AuthenticatedAnalyticsReportsRoute: AuthenticatedAnalyticsReportsRoute,
    AuthenticatedAnalyticsTrafficRoute: AuthenticatedAnalyticsTrafficRoute,
    AuthenticatedAnalyticsIndexRoute: AuthenticatedAnalyticsIndexRoute,
  }

const AuthenticatedAnalyticsRouteRouteWithChildren =
  AuthenticatedAnalyticsRouteRoute._addFileChildren(
    AuthenticatedAnalyticsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRouteRoute: typeof AuthenticatedAnalyticsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedPaymentsGatewayRoute: typeof AuthenticatedPaymentsGatewayRoute
  AuthenticatedUsersUserIdRoute: typeof AuthenticatedUsersUserIdRoute
  AuthenticatedBorzoReportIndexRoute: typeof AuthenticatedBorzoReportIndexRoute
  AuthenticatedCategoryIndexRoute: typeof AuthenticatedCategoryIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedCommissionIndexRoute: typeof AuthenticatedCommissionIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedInventoryManagementIndexRoute: typeof AuthenticatedInventoryManagementIndexRoute
  AuthenticatedOrderIndexRoute: typeof AuthenticatedOrderIndexRoute
  AuthenticatedPaymentsIndexRoute: typeof AuthenticatedPaymentsIndexRoute
  AuthenticatedProductsIndexRoute: typeof AuthenticatedProductsIndexRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
  AuthenticatedSitemapsIndexRoute: typeof AuthenticatedSitemapsIndexRoute
  AuthenticatedTemplateOrdersIndexRoute: typeof AuthenticatedTemplateOrdersIndexRoute
  AuthenticatedTemplateWalletIndexRoute: typeof AuthenticatedTemplateWalletIndexRoute
  AuthenticatedUploadProductsIndexRoute: typeof AuthenticatedUploadProductsIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedVendorAnalyticsIndexRoute: typeof AuthenticatedVendorAnalyticsIndexRoute
  AuthenticatedVendorTemplateAboutIndexRoute: typeof AuthenticatedVendorTemplateAboutIndexRoute
  AuthenticatedVendorTemplateContactIndexRoute: typeof AuthenticatedVendorTemplateContactIndexRoute
  AuthenticatedVendorTemplateOtherIndexRoute: typeof AuthenticatedVendorTemplateOtherIndexRoute
  AuthenticatedVendorTemplatePagesIndexRoute: typeof AuthenticatedVendorTemplatePagesIndexRoute
  AuthenticatedVendorTemplateIndexRoute: typeof AuthenticatedVendorTemplateIndexRoute
  AuthenticatedVendorIndexRoute: typeof AuthenticatedVendorIndexRoute
  AuthenticatedWalletIndexRoute: typeof AuthenticatedWalletIndexRoute
  AuthenticatedCategoryCreateCategoryIndexRoute: typeof AuthenticatedCategoryCreateCategoryIndexRoute
  AuthenticatedProductsAdminProductsIndexRoute: typeof AuthenticatedProductsAdminProductsIndexRoute
  AuthenticatedProductsCreateProductsIndexRoute: typeof AuthenticatedProductsCreateProductsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRouteRoute:
    AuthenticatedAnalyticsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedPaymentsGatewayRoute: AuthenticatedPaymentsGatewayRoute,
  AuthenticatedUsersUserIdRoute: AuthenticatedUsersUserIdRoute,
  AuthenticatedBorzoReportIndexRoute: AuthenticatedBorzoReportIndexRoute,
  AuthenticatedCategoryIndexRoute: AuthenticatedCategoryIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedCommissionIndexRoute: AuthenticatedCommissionIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedInventoryManagementIndexRoute:
    AuthenticatedInventoryManagementIndexRoute,
  AuthenticatedOrderIndexRoute: AuthenticatedOrderIndexRoute,
  AuthenticatedPaymentsIndexRoute: AuthenticatedPaymentsIndexRoute,
  AuthenticatedProductsIndexRoute: AuthenticatedProductsIndexRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
  AuthenticatedSitemapsIndexRoute: AuthenticatedSitemapsIndexRoute,
  AuthenticatedTemplateOrdersIndexRoute: AuthenticatedTemplateOrdersIndexRoute,
  AuthenticatedTemplateWalletIndexRoute: AuthenticatedTemplateWalletIndexRoute,
  AuthenticatedUploadProductsIndexRoute: AuthenticatedUploadProductsIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedVendorAnalyticsIndexRoute:
    AuthenticatedVendorAnalyticsIndexRoute,
  AuthenticatedVendorTemplateAboutIndexRoute:
    AuthenticatedVendorTemplateAboutIndexRoute,
  AuthenticatedVendorTemplateContactIndexRoute:
    AuthenticatedVendorTemplateContactIndexRoute,
  AuthenticatedVendorTemplateOtherIndexRoute:
    AuthenticatedVendorTemplateOtherIndexRoute,
  AuthenticatedVendorTemplatePagesIndexRoute:
    AuthenticatedVendorTemplatePagesIndexRoute,
  AuthenticatedVendorTemplateIndexRoute: AuthenticatedVendorTemplateIndexRoute,
  AuthenticatedVendorIndexRoute: AuthenticatedVendorIndexRoute,
  AuthenticatedWalletIndexRoute: AuthenticatedWalletIndexRoute,
  AuthenticatedCategoryCreateCategoryIndexRoute:
    AuthenticatedCategoryCreateCategoryIndexRoute,
  AuthenticatedProductsAdminProductsIndexRoute:
    AuthenticatedProductsAdminProductsIndexRoute,
  AuthenticatedProductsCreateProductsIndexRoute:
    AuthenticatedProductsCreateProductsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClerkauthRouteRouteChildren {
  ClerkauthSignInRoute: typeof ClerkauthSignInRoute
  ClerkauthSignUpRoute: typeof ClerkauthSignUpRoute
}

const ClerkauthRouteRouteChildren: ClerkauthRouteRouteChildren = {
  ClerkauthSignInRoute: ClerkauthSignInRoute,
  ClerkauthSignUpRoute: ClerkauthSignUpRoute,
}

const ClerkauthRouteRouteWithChildren = ClerkauthRouteRoute._addFileChildren(
  ClerkauthRouteRouteChildren,
)

interface ClerkAuthenticatedRouteRouteChildren {
  ClerkAuthenticatedUserManagementRoute: typeof ClerkAuthenticatedUserManagementRoute
}

const ClerkAuthenticatedRouteRouteChildren: ClerkAuthenticatedRouteRouteChildren =
  {
    ClerkAuthenticatedUserManagementRoute:
      ClerkAuthenticatedUserManagementRoute,
  }

const ClerkAuthenticatedRouteRouteWithChildren =
  ClerkAuthenticatedRouteRoute._addFileChildren(
    ClerkAuthenticatedRouteRouteChildren,
  )

interface ClerkRouteRouteChildren {
  ClerkauthRouteRoute: typeof ClerkauthRouteRouteWithChildren
  ClerkAuthenticatedRouteRoute: typeof ClerkAuthenticatedRouteRouteWithChildren
}

const ClerkRouteRouteChildren: ClerkRouteRouteChildren = {
  ClerkauthRouteRoute: ClerkauthRouteRouteWithChildren,
  ClerkAuthenticatedRouteRoute: ClerkAuthenticatedRouteRouteWithChildren,
}

const ClerkRouteRouteWithChildren = ClerkRouteRoute._addFileChildren(
  ClerkRouteRouteChildren,
)

interface TemplateVendorIdOrdersRouteChildren {
  TemplateVendorIdOrdersOrderIdRoute: typeof TemplateVendorIdOrdersOrderIdRoute
}

const TemplateVendorIdOrdersRouteChildren: TemplateVendorIdOrdersRouteChildren =
  {
    TemplateVendorIdOrdersOrderIdRoute: TemplateVendorIdOrdersOrderIdRoute,
  }

const TemplateVendorIdOrdersRouteWithChildren =
  TemplateVendorIdOrdersRoute._addFileChildren(
    TemplateVendorIdOrdersRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ClerkRouteRoute: ClerkRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  TemplateVendorIdAboutRoute: TemplateVendorIdAboutRoute,
  TemplateVendorIdCartRoute: TemplateVendorIdCartRoute,
  TemplateVendorIdCheckoutRoute: TemplateVendorIdCheckoutRoute,
  TemplateVendorIdContactRoute: TemplateVendorIdContactRoute,
  TemplateVendorIdLoginRoute: TemplateVendorIdLoginRoute,
  TemplateVendorIdOrdersRoute: TemplateVendorIdOrdersRouteWithChildren,
  TemplateVendorIdProfileRoute: TemplateVendorIdProfileRoute,
  TemplateVendorIdRegisterRoute: TemplateVendorIdRegisterRoute,
  TemplateVendorIdIndexRoute: TemplateVendorIdIndexRoute,
  TemplateVendorIdCategoryCategoryIdRoute:
    TemplateVendorIdCategoryCategoryIdRoute,
  TemplateVendorIdPagePageSlugRoute: TemplateVendorIdPagePageSlugRoute,
  TemplateVendorIdProductProductIdRoute: TemplateVendorIdProductProductIdRoute,
  TemplateVendorIdSubcategorySubcategoryIdRoute:
    TemplateVendorIdSubcategorySubcategoryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
